from schemas.map import Map
from schemas.room import Room
from schemas.bonusroom import Bonusroom
from schemas.traproom import Traproom
from schemas.leverroom import Leverroom
from schemas.exitdoor import Exitdoor
from schemas.player import Player
from schemas.score import Score
from schemas.playerpos import Playerpos
from schemas.inventory import Inventory
from schemas.bonusitem import Bonusitem